# What is Numpy

* NumPy stands for Numerical Python.
* NumPy is a Python library used for working with arrays.
* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# Why use Numpy?

* NumPy uses much less memory to store data
* It is Fast
* Mathematical operations on NumPy are easy to perform
* It works very well with SciPy and other Libraries
* It has lots of built-in functions
* It has universal functions

# Features of Numpy-

* NumPy stands on CPython, a non optimizing bytecode interpreter.
* Multidimensional arrays.
* Functions & operators for these arrays
* Python alternatives to MATLAB.
* ndarray- n-dimensional arrays.
* Fourier transforms & shapes manipulation.
* Linear algebra & random number generation.

# Import Numpy

The import numpy statement is used to import the NumPy library in Python.To import NumPy in Python, you can use the following statement:

In [1]:
import numpy as np

# Array Creation

1. numpy.array: Create a NumPy array from a Python list or tuple.
1. numpy.zeros: Create an array filled with zeros.
1. numpy.ones:  Create an array filled with ones.
1. numpy.empty: Create an uninitialized array.
1. numpy.arange:Create an array with regularly spaced values.


In [2]:
array1 = np.array([1, 2, 3], dtype = 'int')

In [3]:
array1

array([1, 2, 3])

In [4]:
zeros = np.zeros((3, 3), dtype = 'int')  # Return a new array of given shape and type, filled with zeros

In [5]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
ones = np.ones((3, 3), dtype = 'int') # Return a new array of given shape and type, filled with ones

In [7]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
full = np.full((2,3), 5) # Return a new array of given shape and type, filled with given value

In [9]:
full

array([[5, 5, 5],
       [5, 5, 5]])

In [10]:
identity = np.identity(3, dtype = 'int') # Return the identity array.

In [11]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
arange = np.arange(1, 10, 2) # Return evenly spaced values within a given interval.

In [13]:
arange

array([1, 3, 5, 7, 9])

In [14]:
empty = np.empty((1,5)) # Return a new array of given shape and type, without initializing entries.

In [15]:
empty

array([[1., 1., 1., 1., 1.]])

# Array Atrributes


* ndarray.shape: Get the dimensions of an array.
* ndarray.dtype: Get the data type of the elements in an array.
* ndarray.ndim: Get the number of dimensions in an array.
* ndarray.size: Get the total number of elements in an array.
* ndarray.itemsize: Get the size in bytes of each element in an array.

In [16]:
a = np.array([1,2,3])

In [17]:
a

array([1, 2, 3])

In [18]:
type(a)

numpy.ndarray

In [19]:
a.shape

(3,)

In [20]:
a.ndim

1

In [21]:
a.dtype

dtype('int64')

In [22]:
a.size

3

In [23]:
a.itemsize

8

# Array indexing and Slicing

**Indexing**

Indexing: Access individual elements in an array using indexing, similar to regular Python lists.


In [24]:
a = np.array([1,2,3,4,5,6])

In [25]:
a

array([1, 2, 3, 4, 5, 6])

In [26]:
a[1]

2

In [27]:
a[5]

6

In [28]:
a[-3]

4

In [29]:
a2 = np.random.randint(1, 10, size = (3,3))

In [30]:
a2

array([[5, 1, 9],
       [2, 5, 4],
       [9, 2, 8]])

In [31]:
a2[2][2]

8

In [32]:
a2[1,1]

5

In [33]:
a3 = np.random.randint(1, 10, size = (2, 3, 3))

In [34]:
a3

array([[[6, 8, 4],
        [1, 6, 4],
        [8, 4, 9]],

       [[4, 4, 8],
        [8, 7, 2],
        [5, 4, 1]]])

In [35]:
a3[0][1][2]

4

**Slicing**

Slicing: Extract a portion of an array by specifying start, end, and step size, similar to regular Python lists.

In [36]:
a

array([1, 2, 3, 4, 5, 6])

In [37]:
a[0:3]

array([1, 2, 3])

In [38]:
a[:4]

array([1, 2, 3, 4])

In [39]:
a[2:]

array([3, 4, 5, 6])

# Manipulating array shapes 
* reshape()
* resize()
* flatten()
* revel()
* defining array shape


**Reshape()**

In [40]:
a = np.array([[1, 2, 3],
            [4, 5, 6]])

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
a.shape

(2, 3)

In [43]:
a_reshaped = np.reshape(a, (3, 2)) # Gives a new shape to an array without changing its data.

In [44]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

**resize()**

In [45]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
a_resized = np.resize(a, (4, 3)) # Return a new array with the specified shape.

In [47]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

**ravel()**

In [48]:
a = np.random.randint(1, 10, (2, 3)) # Return a view of the array

In [49]:
a

array([[8, 4, 2],
       [7, 7, 5]])

In [50]:
a_raveled = np.ravel(a)

In [51]:
a_raveled

array([8, 4, 2, 7, 7, 5])

In [52]:
a_raveled.shape

(6,)

**flatten()**

In [53]:
a

array([[8, 4, 2],
       [7, 7, 5]])

In [54]:
a_flattened = a.flatten() # Return a copy of the array, always allocates a new memory. 

In [55]:
a_flattened

array([8, 4, 2, 7, 7, 5])

In [56]:
a_flattened[0] = 1

In [57]:
a_flattened

array([1, 4, 2, 7, 7, 5])

**Defining an array shape**

In [58]:
a

array([[8, 4, 2],
       [7, 7, 5]])

In [59]:
a.shape = (3, 2)

In [60]:
a

array([[8, 4],
       [2, 7],
       [7, 5]])

# Stacking

In [61]:
b = 2*a

In [62]:
b

array([[16,  8],
       [ 4, 14],
       [14, 10]])

In [63]:
np.hstack((a, b))

array([[ 8,  4, 16,  8],
       [ 2,  7,  4, 14],
       [ 7,  5, 14, 10]])

In [64]:
np.column_stack((a, b))

array([[ 8,  4, 16,  8],
       [ 2,  7,  4, 14],
       [ 7,  5, 14, 10]])

In [65]:
np.concatenate((a, b), axis = 1)

array([[ 8,  4, 16,  8],
       [ 2,  7,  4, 14],
       [ 7,  5, 14, 10]])

**Vertical Stacking**

In [66]:
np.vstack((a, b))

array([[ 8,  4],
       [ 2,  7],
       [ 7,  5],
       [16,  8],
       [ 4, 14],
       [14, 10]])

In [67]:
np.row_stack((a, b))

array([[ 8,  4],
       [ 2,  7],
       [ 7,  5],
       [16,  8],
       [ 4, 14],
       [14, 10]])

In [68]:
np.concatenate((a, b), axis = 0)

array([[ 8,  4],
       [ 2,  7],
       [ 7,  5],
       [16,  8],
       [ 4, 14],
       [14, 10]])

**Depth Stack**

In [69]:
np.dstack((a, b))

array([[[ 8, 16],
        [ 4,  8]],

       [[ 2,  4],
        [ 7, 14]],

       [[ 7, 14],
        [ 5, 10]]])